### ISSUE TITLE
error encountered while doing library validation

### ISSUE THREAD

**Issue by huangjunying** [SNU-HPCS/CryoModel#6] opened 2023-04-11 10:31 UTC
Hello, we encountered some errors while using the code in CryoPipeline for library validation. Specifically, when running "make libtest-ideal", we received the following error:
Error: Cannot open cell TINV_X1.FRAM for read. (MW-004)
Error: Cannot open cell TLAT_X1.FRAM for read. (MW-004)
Error: Cannot open cell XNOR2_X1.FRAM for read. (MW-004)
Error: Cannot open cell XNOR2_X2.FRAM for read. (MW-004)
Error: Cannot open cell XOR2_X1.FRAM for read. (MW-004)
Error: Cannot open cell XOR2_X2.FRAM for read. (MW-004)
Error: Cannot open cell OAI22_X1.FRAM for read. (MW-004)
Error: Cannot open cell OAI22_X2.FRAM for read. (MW-004)
Error: Cannot open cell OAI22_X4.FRAM for read. (MW-004)
Error: Cannot open cell OAI33_X1.FRAM for read. (MW-004)
Error: Cannot open cell OR2_X1.FRAM for read. (MW-004)
Error: Cannot open cell OR2_X2.FRAM for read. (MW-004)
Error: Cannot open cell OR2_X4.FRAM for read. (MW-004)
Error: Cannot open cell OR3_X1.FRAM for read. (MW-004)
Error: Cannot open cell OR3_X2.FRAM for read. (MW-004)
Error: Cannot open cell OR3_X4.FRAM for read. (MW-004)
Error: Cannot open cell OR4_X1.FRAM for read. (MW-004)
Error: Cannot open cell OR4_X2.FRAM for read. (MW-004)
Error: Cannot open cell OR4_X4.FRAM for read. (MW-004)
.....
Logic vs. physical library check summary:
Number of cells missing in physical library:    134 
Information: Logic library is INCONSISTENT with physical library (LIBCHK-220)

Could you please upload the correct Milky library? 
Alternatively, do you have any suggestions on how to solve this problem?

**Comment by ehdans06** [comment] 2023-04-11 12:26
![image](https://user-images.githubusercontent.com/21350262/231160379-9096f162-a020-4b89-b98f-56e278de7a45.png)

Thank you for your interest in CryoModel.
It seems not a library problem because I can see the correct message after running "make libtest-ideal" in our server (as above).
The library in the repository is the valid library.

How about run "make milky-all" before running "make libtest-ideal"?

**Comment by ehdans06** [comment] 2023-04-20 03:30
Due to the absence of a response for a week, I regard the issue is resolved.
I will close this issue.

**Closed by ehdans06** 2023-04-20 03:30 UTC
